[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Public API proxy → Netlify Functions (keep BEFORE SPA rule)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA catch-all LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
