[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# ✅ Public API path that proxies to Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# ✅ SPA catch-all (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
